# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wa-back-postechchallenge2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://postechchallenge2acr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_da639f9d5648475d902e09b1d3a861fc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f6950f1d7d6247dba632761d659a5897 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: postechchallenge2acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_da639f9d5648475d902e09b1d3a861fc }}/aspnetimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wa-back-postechchallenge2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7944ee03aa69498783524ed94a4e40b5 }}
        images: 'postechchallenge2acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_da639f9d5648475d902e09b1d3a861fc }}/aspnetimage:${{ github.sha }}'